#!/usr/bin/perl

open(OUTPUT, "> files.c");

chdir("realfiles");

opendir(DIR, ".");
@files =  grep { !/^\./ && !/(CVS|~)/ } readdir(DIR);
closedir(DIR);

print(OUTPUT "#include \"files.h\"\n\n");

foreach $file (@files) {  
   
    if(-d $file && $file !~ /^\./) {
	print "Processing directory $file\n";
	opendir(DIR, $file);
	@newfiles =  grep { !/^\./ && !/(CVS|~)/ } readdir(DIR);
	closedir(DIR);
	printf "Adding files @newfiles\n";
	@files = (@files, map { $_ = "$file/$_" } @newfiles);
	next;
    }
}

foreach $file (@files) {
    if(-f $file) {
	
	print "Adding file $file\n";
	
	open(FILE, $file) || die "Could not open file $file\n";

	$file =~ s-^-/-;
	$fvar = $file;
	$fvar =~ s-/-_-g;
	$fvar =~ s-\.-_-g;
	# for AVR, add PROGMEM here
	print(OUTPUT "static const unsigned char data".$fvar."[] = {\n");
	print(OUTPUT "\t/* $file */\n\t");
	for($j = 0; $j < length($file); $j++) {
	    printf(OUTPUT "%#02x, ", unpack("C", substr($file, $j, 1)));
	}
	printf(OUTPUT "0,\n");
	
	
	$i = 0;        
	while(read(FILE, $data, 1)) {
	    if($i == 0) {
		print(OUTPUT "\t");
	    }
	    printf(OUTPUT "%#02x, ", unpack("C", $data));
	    $i++;
	    if($i == 10) {
		print(OUTPUT "\n");
		$i = 0;
	    }
	}
	print(OUTPUT "0};\n\n");
	close(FILE);
	push(@fvars, $fvar);
	push(@pfiles, $file);
    }
}

print(OUTPUT "const struct embedded_file embfile[]={\n");

for($i = 0; $i < @fvars; $i++) {
    $file = $pfiles[$i];
    $fvar = $fvars[$i];

    if($i == 0) {
        $prevfile = "NULL";
    } else {
        $prevfile = "file" . $fvars[$i - 1];
    }
    print(OUTPUT "  {data$fvar ,data$fvar + ". (length($file) + 1) .", ");
    print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) ."},\n");
}
print(OUTPUT "};\n");

chdir("../");
open(OUTPUT, "> files.h");


print(OUTPUT "#ifndef FILES_H_\n");
print(OUTPUT "#define FILES_H_\n\n");
print(OUTPUT "#define NR_OF_EMBFILES         $i\n\n");
print(OUTPUT "struct embedded_file{\n");
print(OUTPUT "  const unsigned char * filename;\n");
print(OUTPUT "  const unsigned char * data;\n");
print(OUTPUT "  long size;\n");
print(OUTPUT "};\n\n");
print(OUTPUT "const struct embedded_file embfile[NR_OF_EMBFILES];\n\n");
print(OUTPUT "#endif /* FILES_H_ */\n");
