#ifndef BOOTLOADERCONFIG_H
#define BOOTLOADERCONFIG_H

#include "dev/flash.h"

extern uint32_t _sfixed;
extern uint32_t _header;

#define FIRMWARE_MEM_HEADER_OFFSET          ((unsigned long)(&_header) - (unsigned long)(&_sfixed))

#define FIRMWARE_MEM_HEADER_SIGNATURE       FIRMWARE_MEM_HEADER_OFFSET + 0
#define FIRMWARE_MEM_HEADER_VERSION         FIRMWARE_MEM_HEADER_OFFSET + 8
#define FIRMWARE_MEM_HEADER_LOAD_ADDRESS    FIRMWARE_MEM_HEADER_OFFSET + 12
#define FIRMWARE_MEM_HEADER_START_ADDRESS   FIRMWARE_MEM_HEADER_OFFSET + 16
#define FIRMWARE_MEM_HEADER_END_ADDRESS     FIRMWARE_MEM_HEADER_OFFSET + 20

#define APPLICATION_FW_START_ADDRESS        0x00010000
#define APPLICATION_FW_MAX_SIZE             0x00030000
#define APPLICATION_FW_VERSION              APPLICATION_FW_START_ADDRESS + FIRMWARE_MEM_HEADER_VERSION

#define BOOTLOADER_PARAMS_FLASH             INTERNAL_FLASH
#define BOOTLOADER_FW_START_ADDRESS         0x00000000
#define BOOTLOADER_FW_VERSION               BOOTLOADER_FW_START_ADDRESS + FIRMWARE_MEM_HEADER_VERSION
#define BOOTLOADER_PARAMS_START_ADDRESS     0x00008000

#define BACKUP_FW_START_ADDRESS             0
#define DOWNLOAD_FW_START_ADDRESS           0

#endif // BOOTLOADERCONFIG_H
